server:  
  port: ${port:9400}

spring:  
  application:
    name: product-service

endpoints:
    shutdown:
      enabled: true
      sensitive: false

envoy:
  discovery:
    url: http://localhost:9200